### PR TITLE
addressing #50 and #30

### PR DESCRIPTION
**Pull request by malawrim**
changed total_plants to total_hosts in simulation
renamed short_long_kernel to natural_anthropogenic_kernel and related parameter names

### CODE REVIEW

**Comment by malawrim** [comment]
For #30 I only renamed the parameters, I was not sure how to address the second part of the issue (parametrize usage of the kernels) because I did not fully understand the issue. Are you wanting multiple ways to call the function? (i.e one excludes natural and the other excludes anthropogenic?)

**Comment by malawrim** [comment]
For #50 the only major issue I saw was with total_plants, however I also considered changing pesticideTreatment class name to be more general (i.e chemicalTreatment) because I am not sure pesticides can be related to animals. But, I was not sure about this, so I can make/not make this change based on your input.

**Comment by wenzeslaus** [comment]
Great, this looks good, but I have to look in more detail for the review.

@malawrim Can you please remove the `.DS_Store` file? Simple `git rm` (+commit & push) will be enough (we will Squash it here, so the history will be clean). You can add `.DS_Store` to `.gitignore` and add that to this PR if you want.

**Comment by wenzeslaus** [comment]
> I was not sure how to address the second part of the issue (parametrize usage of the kernels)

That was something to keep in mind if there is a need for it, but so far we don't have a need to generalize that, e.g., use only the second kernel. This can be also addressed on different levels including user code, so we don't have to worry about this now in the library.

**Comment by wenzeslaus** [comment]
> ...I also considered changing pesticideTreatment class name to be more general (i.e chemicalTreatment) because I am not sure pesticides can be related to animals.

Good point, but I don't have any strong opinion either, let's change it once the other use cases become clear.

Thanks for catching the typos @malawrim.

**Pull request merged**
